src/Entity/Customers.php
<?php

namespace App\Entity;

use App\Repository\CustomersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomersRepository::class)]
class Customers
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $url_project = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $slug;
    /**
     * @var Collection<int, Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'customers')]
    private Collection $tags;

    /**
     * @var Collection<int, Image>
     */
    #[ORM\ManyToMany(targetEntity: Image::class, cascade: ['persist', 'remove'])]
    private Collection $images;


    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->slug = $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getUrlProject(): ?string
    {
        return $this->url_project;
    }

    public function setUrlProject(string $url_project): static
    {
        $this->url_project = $url_project;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        $this->images->removeElement($image);

        return $this;
    }
    public function getSlug(): ?string
    {
        return $this->slug;
    }
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Url = null;

    #[ORM\Column(length: 255)]
    private ?string $Alt = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->Url;
    }

    public function setUrl(string $Url): static
    {
        $this->Url = $Url;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->Alt;
    }

    public function setAlt(string $Alt): static
    {
        $this->Alt = $Alt;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }
}

src/Form/CustomersType.php
<?php

namespace App\Form;

use App\Entity\Tag;
use App\Form\ImageType;
use App\Entity\Customers;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class CustomersType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void {

        $builder
            ->add('name')
            ->add('url_project')
            ->add('tags', EntityType::class, [
                'class' => Tag::class,
                'choice_label' => 'name',
                'multiple' => true,
            ])
            ->add('images', CollectionType::class, [
                'entry_type' => ImageType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'prototype' => true,
                'prototype_name' => '__name__',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void {
        
        $resolver->setDefaults([
            'data_class' => Customers::class,
        ]);
    }
}

src/Controller/CustomersController.php
<?php

namespace App\Controller;

use App\Entity\Customers;
use App\Form\CustomersType;
use App\Repository\CustomersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

#[Route('/customers')]
class CustomersController extends AbstractController {

    private $manager;
    public function __construct(EntityManagerInterface $manager) {
        $this->manager = $manager;
    }

    #[Route(name: 'app_customers_index', methods: ['GET'])]
    public function index(CustomersRepository $customersRepository): Response
    {
        return $this->render('customers/index.html.twig', [
            'customers' => $customersRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_customers_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SluggerInterface $slugger): Response {
        $customer = new Customers();
        $form = $this->createForm(CustomersType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($form->get('images') as $imageForm) {
                $imageFile = $imageForm->get('image')->getData();

                if ($imageFile) {
                    $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();

                    try {
                        $imageFile->move(
                            $this->getParameter('images_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // handle exception if something happens during file upload
                    }

                    $image = $imageForm->getData();
                    $image->setUrl('/uploads/images/'.$newFilename);
                    $customer->addImage($image);

                    // Appeler explicitement persist sur chaque entité Image
                    $this->manager->persist($image);
                }
            }

            $this->manager->persist($customer);
            $this->manager->flush();

            return $this->redirectToRoute('app_customers_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('customers/new.html.twig', [
            'customer' => $customer,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_customers_show', methods: ['GET'])]
    public function show(Customers $customer): Response
    {
        return $this->render('customers/show.html.twig', [
            'customer' => $customer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_customers_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Customers $customer, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(CustomersType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($form->get('images') as $imageForm) {
                $imageFile = $imageForm->get('image')->getData();

                if ($imageFile) {
                    $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();

                    try {
                        $imageFile->move(
                            $this->getParameter('images_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // handle exception if something happens during file upload
                    }

                    // Supprimer l'ancien fichier si nécessaire
                    if ($imageForm->getData()->getUrl()) {
                        $oldFilePath = $this->getParameter('images_directory').'/'.basename($imageForm->getData()->getUrl());
                        if (file_exists($oldFilePath)) {
                            unlink($oldFilePath);
                        }
                    }

                    $image = $imageForm->getData();
                    $image->setUrl('/uploads/images/'.$newFilename);
                    $customer->addImage($image);

                    // Appeler explicitement persist sur chaque entité Image
                    $this->manager->persist($image);
                }
            }

            $this->manager->flush();

            return $this->redirectToRoute('app_customers_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('customers/edit.html.twig', [
            'customer' => $customer,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}/delete', name: 'app_customers_delete', methods: ['POST'])]
    public function delete(Request $request, Customers $customer): Response {

        if ($this->isCsrfTokenValid('delete'.$customer->getId(), $request->request->get('_token'))) {
            // Supprimer les images associées
            foreach ($customer->getImages() as $image) {
                $oldFilePath = $this->getParameter('images_directory').'/'.basename($image->getUrl());
                if (file_exists($oldFilePath)) {
                    unlink($oldFilePath);
                }
                $this->manager->remove($image);
            }

            $this->manager->remove($customer);
            $this->manager->flush();
        }

        return $this->redirectToRoute('app_customers_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/customers/_delete_form.html.twig
<form method="post" action="{{ path('app_customers_delete', {'id': customer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ customer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/customers/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le client{% endblock %}

{% block body %}
    <h1>Modifier le client</h1>

    {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.url_project) }}
        {{ form_row(form.tags) }}

        <h2>Images</h2>
        <div id="images_container" data-prototype="{{ form_widget(form.images.vars.prototype)|e }}">
            {% for imageForm in form.images %}
                <div class="image-entry m-4">
                    {% if imageForm.vars.value.url %}
                        <img src="{{ asset(imageForm.vars.value.url) }}" alt="{{ imageForm.vars.value.alt }}" style="max-width: 200px;">
                    {% endif %}
                    {{ form_row(imageForm.image) }}
                    {{ form_row(imageForm.Alt) }}
                    {{ form_row(imageForm.Title) }}
                </div>
            {% endfor %}
        </div>

        <button type="button" id="add_image_button">Ajouter une image</button>

        <button type="submit">Enregistrer</button>
    {{ form_end(form) }}

    <a href="{{ path('app_customers_index') }}">Retour à la liste</a>
{% endblock %}

templates/customers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customers index{% endblock %}

{% block body %}
    <h1>Customers index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Url_project</th>
                <th>Tags</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for customer in customers %}
            <tr>
                <td>{{ customer.id }}</td>
                <td>{{ customer.name | capitalize}}</td>
                <td>{{ customer.urlProject }}</td>
                <td>
                    {% for tag in customer.tags %}
                        {{ tag.name |capitalize }}{% if not loop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <a href="{{ path('app_customers_show', {'id': customer.id}) }}">show</a>
                    <a href="{{ path('app_customers_edit', {'id': customer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_customers_new') }}">Create new</a>
{% endblock %}

templates/customers/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un client{% endblock %}

{% block body %}
    <h1>Ajouter un client</h1>

    {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.url_project) }}
        {{ form_row(form.tags) }}

        <h2>Images</h2>
        <div id="images_container" data-prototype="{{ form_widget(form.images.vars.prototype)|e }}">
            {% for imageForm in form.images %}
                <div class="image-entry">
                    {{ form_row(imageForm.image) }}
                    {{ form_row(imageForm.Alt) }}
                    {{ form_row(imageForm.Title) }}
                </div>
            {% endfor %}
        </div>

        <button type="button" id="add_image_button">Ajouter une image</button>

        <button type="submit">Enregistrer</button>
    {{ form_end(form) }}

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            let collectionHolder = document.querySelector('#images_container');
            let addButton = document.querySelector('#add_image_button');

            // Récupérer le nombre actuel d'entrées dans la collection
            let index = collectionHolder.children.length;

            // Fonction pour ajouter un nouveau formulaire d'image
            function addImageForm() {
                // Récupérer le prototype de formulaire
                let prototype = collectionHolder.dataset.prototype;

                // Remplacer '__name__' dans le prototype par l'index actuel
                let newForm = prototype.replace(/__name__/g, index);

                // Incrémenter l'index pour le prochain élément
                index++;

                // Créer un élément div pour le nouveau formulaire
                let newFormElement = document.createElement('div');
                newFormElement.classList.add('image-entry');
                newFormElement.innerHTML = newForm;

                // Ajouter le nouveau formulaire au conteneur
                collectionHolder.appendChild(newFormElement);
            }

            // Ajouter un gestionnaire d'événements au bouton d'ajout
            addButton.addEventListener('click', function(e) {
                e.preventDefault();
                addImageForm();
            });
        });
    </script>
{% endblock %}

templates/customers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customers{% endblock %}

{% block body %}
    <h1>Customers</h1>
    <table class="table">
        <tbody>

            <tr>
                <th>Id</th>
                <td>{{ customer.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ customer.name }}</td>
            </tr>
            <tr>
                <th>Url_project</th>
                <td>{{ customer.urlProject }}</td>
            </tr>
            <tr>
                <th>Tags</th>
                <td>
                    {% for tag in customer.tags %}
                        {{ tag.name }}{% if not loop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td>Images</td>
                <td>
                    {% for image in customer.images %}
                        <img style="display:inline;max-width:20rem; margin-right:0.5rem" src="{{ image.url }}" alt="{{image.Alt}}" title="{{image.title}}">
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_customers_index') }}">back to list</a>

    <a href="{{ path('app_customers_edit', {'id': customer.id}) }}">edit</a>

    {{ include('customers/_delete_form.html.twig') }}
{% endblock %}